// <auto-generated />
namespace MovieCustomerMVAAppWithAuthentication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DOBColumnaddedincustomertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DOBColumnaddedincustomertable));
        
        string IMigrationMetadata.Id
        {
            get { return "202008201253022_DOB Column added in customer table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
